app/models/__init__.py
from .group import Group
from .student import Student, student_group_assoc_table
from .lessons import Lesson, lesson_group_assoc_table

app/models/group.py
from __future__ import annotations

from typing import List

from sqlalchemy import String
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.database import Base
from .lessons import lesson_group_assoc_table, Lesson


class Group(Base):
    __tablename__ = "groups"

    id: Mapped[int] = mapped_column(primary_key=True)
    name: Mapped[str] = mapped_column(String(50))
    lessons: Mapped[List[Lesson]] = relationship(Lesson, secondary=lesson_group_assoc_table, back_populates="groups")

    def __repr__(self):
        return f"Group: {self.name}"

app/models/lessons.py
from __future__ import annotations

from typing import List

from sqlalchemy import String, Table, Column, ForeignKey
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.database import Base


lesson_group_assoc_table = Table(
    "lesson_group_assoc_table",
    Base.metadata,
    Column(
        "group_id",
        ForeignKey("groups.id"),
        primary_key=True
    ),
    Column(
        "lesson_id",
        ForeignKey("lessons.id"),
        primary_key=True
    )
)


class Lesson(Base):
    __tablename__ = "lessons"

    id: Mapped[int] = mapped_column(primary_key=True)
    title: Mapped[str] = mapped_column(String(150))
    groups: Mapped[List["app.models.group.Group"]] = relationship("app.models.group.Group",
                                                                  secondary=lesson_group_assoc_table,
                                                                  back_populates="lessons")

    def __repr__(self):
        group_names = ', '.join([group.name for group in self.groups])
        return f"Lesson: {self.title} (Groups: {group_names})"

app/models/student.py
from __future__ import annotations

from typing import Optional, List

from sqlalchemy import String, Table, Column, ForeignKey
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.database import Base
from .group import Group

student_group_assoc_table = Table(
    "student_group_assoc_table",
    Base.metadata,
    Column(
        "group_id",
        ForeignKey("groups.id"),
        primary_key=True
    ),
    Column(
        "student_id",
        ForeignKey("student.id"),
        primary_key=True
    )
)


class Student(Base):
    __tablename__ = "student"

    id: Mapped[int] = mapped_column(primary_key=True)
    name: Mapped[str] = mapped_column(String(50))
    surname: Mapped[Optional[str]]
    age: Mapped[int]
    address: Mapped[str] = mapped_column(String(255))
    groups: Mapped[List[Group]] = relationship(secondary=student_group_assoc_table)

    def __repr__(self):
        return f"{self.name.title()} {self.surname.title()} Age: {self.age}"

app/__init__.py
from flask import Flask
from app.database import create_db, drop_db


def create_app():
    app = Flask(__name__)

    from app.routes import default_bp, group_bp, student_bp, lesson_bp

    app.register_blueprint(default_bp, url_prefix="/")
    app.register_blueprint(group_bp, url_prefix="/groups/")
    app.register_blueprint(student_bp, url_prefix="/students/")
    app.register_blueprint(lesson_bp, url_prefix="/lessons/")

    from app import models
    create_db() # створення табличок
    # drop_db() # дропнути всі таблички

    return app

app/routes/__init__.py
from .default import bp as default_bp
from .group import bp as group_bp
from .student import bp as student_bp
from .lesson import bp as lesson_bp

app/routes/default.py
from flask import render_template
from flask.blueprints import Blueprint

bp = Blueprint("default", __name__)


@bp.route('/')
def main():
    return render_template("main.html")

app/routes/group.py
from flask import render_template, request
from flask.blueprints import Blueprint
from sqlalchemy import select

from app.database import Session
from app.models import Group

bp = Blueprint("group", __name__)


@bp.route('/', methods=["GET", "POST"])
def group_add():
    with Session() as session:
        if request.method == "POST":
            new_group = Group(name=request.form.get("name"))
            session.add(new_group)
            session.commit()

        groups = session.query(Group).all()
    return render_template("group/managment.html", groups=groups)


@bp.route('/<int:id>', methods=["GET"])
def group_get(id):
    with Session() as session:
        query = select(Group).where(Group.id == id)
        print(query)
        data = session.scalars(query).first()
    return render_template("main.html", content=data)

app/routes/lesson.py
from sqlalchemy import select
from flask import render_template, request, redirect, url_for
from flask.blueprints import Blueprint
from sqlalchemy.orm import selectinload
from app.database import Session
from app.models import Lesson, Group

bp = Blueprint("lesson", __name__)


@bp.route('/', methods=["GET", "POST"])
def lesson_add():
    if request.method == "POST":
        with Session() as session:
            title = request.form.get("title")
            group_ids = [int(group_id) for group_id in request.form.getlist("groups")]

            items_groups = session.query(Group).filter(Group.id.in_(group_ids)).all()

            new_lesson = Lesson(title=title)
            new_lesson.groups = items_groups

            session.add(new_lesson)
            session.commit()

            return redirect(url_for('lesson.lesson_add'))

    with Session() as session:
        lessons = session.query(Lesson).options(selectinload(Lesson.groups)).all()
        groups = session.query(Group).all()

    return render_template("lesson/managment.html", lessons=lessons, groups=groups)


@bp.route('/<int:id>', methods=["GET"])
def lesson_get(id):
    with Session() as session:
        query = select(Lesson).where(Lesson.id == id).options(selectinload(Lesson.groups))
        lesson = session.execute(query).scalar()

    return render_template("main.html", content=lesson)

app/routes/student.py
from datetime import datetime

from flask import render_template, request
from flask.blueprints import Blueprint
from sqlalchemy import select

from app.database import Session
from app.models import Student, Group

bp = Blueprint("student", __name__)


def get_age(birhdate):
    birhdate = datetime.strptime(birhdate, "%Y-%m-%d")
    current_date = datetime.now()
    age = current_date.year - birhdate.year - (
            (current_date.month, current_date.day) < (birhdate.month, birhdate.day)
    )
    return age


@bp.route('/', methods=["GET", "POST"])
def student_add():
    with Session() as session:
        if request.method == "POST":
            print(request.form.get("groups"))
            items_groups = session.query(Group).where(Group.id.in_([request.form.get("groups"), ])).all()
            new_student = Student(
                name=request.form.get("name"),
                surname=request.form.get("surname"),
                age=get_age(request.form.get("birthdate")),
                address=request.form.get("address"),
                groups=items_groups,
            )
            session.add(new_student)
            session.commit()

        students = session.query(Student).all()
        groups = session.query(Group).all()
    return render_template("student/managment.html", students=students, groups=groups)


@bp.route('/<int:id>', methods=["GET"])
def student_get(id):
    with Session() as session:
        query = select(Student).where(Student.id == id)
        print(query)
        data = session.scalars(query).first()
    return render_template("main.html", content=data)

app/templates/base.html
<!DOCTYPE html>
<html lang="uk">
<head>
    <meta charset="UTF-8">
    <ul>
        <li><a href="{{ url_for('group.group_add') }}">Групи</a></li>
        <li><a href="{{ url_for('student.student_add') }}">Студенти</a></li>
        <li><a href="{{ url_for('lesson.lesson_add') }}">Уроки</a></li>
    </ul>
    <title>Document</title>
</head>
<body>
{% block nav%}
{% endblock nav%}

{% block main%}
{% endblock main%}

{% block footer%}
{% endblock footer%}
</body>
</html>

app/templates/group/managment.html
{% extends 'base.html' %}

{% block main %}
    {% if groups %}
        <table>
        {% for group in groups %}
            <tr>
                <td>
                    <a href="{{ url_for('group.group_get', id=group.id) }}">{{ group }}</a>
                </td>
            </tr>
        {% endfor %}
        </table>
    {% else %}
        <h1>Відсутні будь-які елементи</h1>
    {% endif%}

    <form action="{{ url_for('group.group_add') }}" method="post">
        <p>
            <label for="name">Name</label>
            <input type="text" id="name" name="name" required>
        </p>
        <p>
            <button type="submit">ADD</button>
            <button type="reset">RESET</button>
        </p>
    </form>
{% endblock main %}

app/templates/lesson/add.html
{% block title %}
    Управління групами
{% endblock title %}

{% block main %}
    <ul>
        {% for group in groups %}
            <li>{{ group.name }}</li>
        {% endfor %}
    </ul>

    <form method="post" action="{{ url_for('group.group_add') }}">
        <label for="name">Назва групи:</label>
        <input type="text" id="name" name="name" required>
        <button type="submit">Додати групу</button>
    </form>
{% endblock main %}

app/templates/lesson/managment.html
{% extends 'base.html' %}

{% block title %}
    Управління уроками
{% endblock title %}

{% block main %}
    <h1>Управління уроками</h1>

    <ul>
        {% for lesson in lessons %}
            <li>
                {{ lesson.title }}
                {% if lesson.groups %}
                    (Група:
                    {% for group in lesson.groups %}
                        {{ group.name }}{% if not loop.last %}, {% endif %}
                    {% endfor %}
                    )
                {% endif %}
            </li>
        {% endfor %}
    </ul>

    <form method="post" action="{{ url_for('lesson.lesson_add') }}">
        <label for="title">Назва уроку:</label>
        <input type="text" id="title" name="title" required>

        <label for="groups">Група:</label>
        <select id="groups" name="groups" multiple>
            {% for group in groups %}
                <option value="{{ group.id }}">{{ group.name }}</option>
            {% endfor %}
        </select>

        <button type="submit">Додати урок</button>
    </form>
{% endblock main %}

app/templates/main.html
{% extends 'base.html' %}

{% block title %}
    Уроки
{% endblock title %}

{% block main %}
    <h1>Сторінка уроків</h1>
{% endblock main %}

app/templates/student/managment.html
{% extends 'base.html' %}
{% block main %}
    {% if students %}
        <table>
        {% for student in students %}
            <tr>
                <td>
                    <a href="{{ url_for('student.student_get', id=student.id) }}">{{ student }}</a>
                </td>
            </tr>
        {% endfor %}
        </table>
    {% else %}
        <h1>Відсутні будь-які елементи</h1>
    {% endif%}

    <form action="{{ url_for('student.student_add') }}" method="post">
        <p>
            <label for="name">Name</label>
            <input type="text" id="name" name="name" required>
        </p>
        <p>
            <label for="surname">Surname</label>
            <input type="text" id="surname" name="surname" required>
        </p>
        <p>
            <label for="birthdate">Birth date</label>
            <input type="date" id="birthdate" name="birthdate" required>
        </p>
        <p>
            <label for="address">Address</label>
            <input type="text" id="address" name="address" required>
        </p>
        <p>
            <label for="groups">Groups</label>
            <select id="groups" name="groups" multiple>
                {% for group in groups %}
                    <option value="{{ group.id }}" {% if group.selected %}selected{% endif%}> {{ group }}</option>
                {% endfor %}
            </select>
        </p>
        <p>
            <button type="submit">ADD</button>
            <button type="reset">RESET</button>
        </p>
    </form>
{% endblock main %}